### ISSUE TITLE
Consider adding to Kicad package repository

### ISSUE THREAD

**Issue by perigoso** [openinput-fw/openinput-kicad-library#2]
https://gitlab.com/kicad/addons/metadata

Not sure If we do this now or we wait for a couple more footprints (right we only have 3 or so, so it feels small to be pushing upstream)

**Comment by FFY00** [comment]
How is the integration with git/vcs of Kicad package repos? Currently, we need to add a submodule to the git repo of the hardware designs, I was hoping this would help with that.

**Comment by perigoso** [comment]
with kicad v6 we will no longer need to have the libraries attached to the hardware repos, as now the symbol and footprint information is embbeded in the project files (footprints already were, but not symbols). 

E: the only information we will lose is the 3d view of the models, but as long as you have this package installed it should show them

**Comment by perigoso** [comment]
Decided to try merge it upstream, don't see any major reasons why not
https://gitlab.com/kicad/addons/metadata/-/merge_requests/24
